### ISSUE TITLE
Manifest issue in version 2.13.0 ? failing in runtime

### ISSUE THREAD

**Issue by mosheeshel** [DataDog/java-dogstatsd-client#159]
Seems like the latest version 2.13.0 - introduced a runtime issue
this is the error we get (just by adding the client to the path as a dependency)
```
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/home/moshee/.gradle/caches/modules-2/files-2.1/org.parboiled/parboiled-java/1.1.7/2298c64ce8ee8e2fb37e97e16d7be52f0c7cf61f/parboiled-java-1.1.7.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.parboiled.transform.AsmUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
java.lang.RuntimeException: Error creating extended parser class: null
        at org.parboiled.Parboiled.createParser(Parboiled.java:58)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:73)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:47)
        at org.scalatest.tools.HtmlReporter.<init>(HtmlReporter.scala:117)
        at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:192)
        at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:239)
        at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:248)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
        at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:247)
        at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:251)
        at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1507)
        at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
        at org.scalatest.tools.Runner$.main(Runner.scala:827)
        at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.IllegalStateException
        at org.objectweb.asm.tree.analysis.BasicInterpreter.<init>(BasicInterpreter.java:66)
        at org.parboiled.transform.RuleMethodInterpreter.<init>(RuleMethodInterpreter.java:42)
        at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:41)
        at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62)
        at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45)
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)

```

Managed to find this reference - old but might be helpful
https://github.com/sirthias/pegdown/issues/62

**Comment by mosheeshel** [comment]
This seems to be related to ScalaTest?
