### ISSUE TITLE
BufferOverflowException when sending events with large text bodies

### ISSUE THREAD

**Issue by NeVeX** [DataDog/java-dogstatsd-client#23]
Using version `2.3`.

Not sure if this is limitation or not, but I could not find an obvious answer. 
When sending events with the text body larger than the buffer limit (1400 bytes in the `2.3` version), a BufferOverflowException occurs. 
When building the `Event` object, there's no mention of the body size limit, perhaps there needs to be? Or can there be a way to handle events with big/larger text bodies? 

An example of the exception received in the handler I register with the client looks like: 
```txt
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at com.timgroup.statsd.NonBlockingStatsDClient$QueueConsumer.run(NonBlockingStatsDClient.java:872)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aantono** [comment]
Looks related to #17

**Comment by schilling** [comment]
@NeVeX once #66 is merged in you can configure the buffer limit and #65 proactively looks for messages over the limit so they're passed to the client's error handler. Do those two changes in conjunction sufficiently help you here?

**Comment by NeVeX** [comment]
Hi @schilling, I think the new configuration options and error handling will help me for sure, thanks.
